title: "Engineering Portfolio – Krishnaraj Venkatesan"
description: "Backend, Distributed Systems & AI Portfolio"
# Use a fully custom layout (no GitHub theme footer/button)
theme: null

# Apply the custom layout to all Markdown pages by default
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional: nicer Markdown + kramdown settings
markdown: kramdown
kramdown:
  input: GFM
